services:
  web:
    container_name: apache
    image: httpd:latest
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./paginas:/var/www/html
      - ./conf:/usr/local/apache2/conf:rw